CREATE TABLE "GCG_4869_COPY"(
 "PART_NUMBER" CHAR(20),
 "LOCN" CHAR(2),
 "STD_COST" NUMERIC(14,4),
 "ORDER_QTY" NUMERIC(14,4),
 "RECVD_COST" NUMERIC(14,4),
 "RECVD_QTY" NUMERIC(14,4),
 "VARIANCE" NUMERIC(11,6),
 "RECVD_DATE" DATE,
 "PO_NUMBER" CHAR(7),
 "RECEIVER_NUMBER" CHAR(6),
 "PartLocn" CHAR(23),
 "PL" CHAR(2),
 "Sequence" CHAR(50));
